import './globals.css'
import { Fragment } from 'react'
import type { Metadata } from 'next'
import { Navbar } from '@/components'
import localFont from 'next/font/local'

const font = localFont({
  src: [
    {
      path: '../../public/fonts/GeneralSans-Variable.woff2',
      style: 'normal'
    },
    {
      path: '../../public/fonts/GeneralSans-VariableItalic.woff2',
      style: 'italic'
    },
  ]
})

export const metadata: Metadata = {
  title: 'Sitemark',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased bg-bg-main dark:bg-bg-main-dark text-text-clr dark:text-text-clr-dark`}>
        <Navbar />
        <Fragment>
          {children}
        </Fragment>
      </body>
    </html>
  )
}
